import {useMemo, useState, Fragment} from 'react';
import {Search, Download, ChevronDown, ArrowUpDown, Check, X} from 'lucide-react';
import {tiers} from '../data/tiers';
import './Leaderboard.css';
import {asset} from '../lib/assets';
const modelLogos:Record<string,string>={"SolarWM-H3": "cuhksz", "Lyra2": "nvidia", "EVOKE": "alaya", "Echo-WM": "jd-official", "Gen3C": "nvidia", "Matrix game 3.5": "skywork", "AlayaWorld": "alaya", "Genie3": "deepmind", "LingBot-World v2": "robbyant", "HY-WorldPlay": "tencent", "SANA-WM": "nvidia", "HappyOyster": "alibaba", "Cosmos3-Nano": "nvidia", "LingBot-World v1": "robbyant", "Voyager": "tencent", "DreamX-World": "amap", "FantasyWorld": "amap", "ABot-World": "amap", "Astra": "tsinghua", "Seedance2.5": "bytedance", "Kling3.0": "kuaishou", "Cosmos3-Super": "nvidia", "HunyuanVideo1.5": "tencent", "MiniMax-H3": "minimax", "LTX2.5": "lightricks", "Wan2.7": "alibaba", "LongCat": "meituan-official"};

export type LeaderboardRow = {id:string;name:string;group:string;interface:string;size:string;steps:string;representation:boolean|null;scores:number[];overall:number;logo?:string};
type Props={rows:LeaderboardRow[]};
const format=(n:number)=>Number.isFinite(n)?n.toFixed(2):'—';
export default function Leaderboard({rows}:Props){
 const [search,setSearch]=useState(''),[control,setControl]=useState('All'),[sort,setSort]=useState(-1),[ascending,setAscending]=useState(false),[selected,setSelected]=useState<string[]>([]),[onlySelected,setOnlySelected]=useState(false),[expanded,setExpanded]=useState<string|null>(null);
 const score=(row:LeaderboardRow,index:number)=>index===-1?row.overall:row.scores[index];
 const filtered=useMemo(()=>rows.filter(r=>r.name.toLowerCase().includes(search.toLowerCase())&&(control==='All'||r.interface===control)&&(!onlySelected||selected.includes(r.id))),[rows,search,control,selected,onlySelected]);
 const sorted=filtered.slice().sort((a,b)=>(ascending?1:-1)*(score(a,sort)-score(b,sort))); 
 const rank=(row:LeaderboardRow,index:number)=>rows.slice().sort((a,b)=>score(b,index)-score(a,index)).findIndex(r=>r.id===row.id)+1;
 const changeSort=(index:number)=>{if(sort===index)setAscending(!ascending);else {setSort(index);setAscending(false);}};
 const toggle=(id:string)=>setSelected(old=>old.includes(id)?old.filter(s=>s!==id):[...old,id]);
 const download=()=>{const quote=(v:string)=>`"${v.replaceAll('"','""')}"`;const content=[['Model','Control interface','Overall',...tiers.map(t=>t.name),'Parameters (B)','Steps','3D representation'].map(quote).join(','),...sorted.map(r=>[r.name,r.interface,format(r.overall),...r.scores.map(format),r.size,r.steps,r.representation===null?'Unknown':r.representation?'Yes':'No'].map(quote).join(','))].join('\r\n');const url=URL.createObjectURL(new Blob([content],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download='orbia-leaderboard.csv';a.click();URL.revokeObjectURL(url);};
 return <div className="lb-panel">
  <div className="lb-tools"><label className="lb-search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search 27 models" aria-label="Search models"/></label><label className="lb-filter">Control interface <select value={control} onChange={e=>setControl(e.target.value)}><option>All</option><option>Camera</option><option>Action</option><option>Text</option></select></label><div className="lb-actions"><a className="lb-submit" href="https://github.com/worldbench/orbia/blob/main/docs/submission.md" target="_blank" rel="noreferrer">Submit your model ↗</a><button className="lb-download" onClick={download}><Download size={16}/> Export CSV</button></div></div>
  {selected.length>0&&<div className="lb-selection"><span><Check size={15}/>{selected.length} selected</span><button className={onlySelected?'active':''} onClick={()=>setOnlySelected(!onlySelected)}>{onlySelected?'Show all models':'Show selected only'}</button><button onClick={()=>{setSelected([]);setOnlySelected(false)}}><X size={14}/>Clear</button></div>}
  <div className="lb-scroll" tabIndex={0} aria-label="Scrollable leaderboard"><table className="lb-table"><thead><tr><th className="lb-model-heading">Model</th><th aria-sort={sort===-1?(ascending?'ascending':'descending'):'none'}><button onClick={()=>changeSort(-1)} aria-label={`Sort by overall ${sort===-1&&!ascending?'ascending':'descending'}`}>Overall <ArrowUpDown size={13}/></button></th>{tiers.map((tier,i)=><th key={tier.id} aria-sort={sort===i?(ascending?'ascending':'descending'):'none'} style={{'--tier-color':tier.color} as React.CSSProperties}><button onClick={()=>changeSort(i)} title={tier.description} aria-label={`Sort by ${tier.name}`}>{tier.short}<ArrowUpDown size={13}/></button></th>)}</tr></thead><tbody>
  {sorted.map(row=><Fragment key={row.id}><tr className={`lb-row ${selected.includes(row.id)?'selected':''}`}><th scope="row"><div className="lb-model"><input type="checkbox" checked={selected.includes(row.id)} onChange={()=>toggle(row.id)} aria-label={`Select ${row.name}`}/><button onClick={()=>setExpanded(expanded===row.id?null:row.id)} aria-expanded={expanded===row.id}><img className={`lb-logo ${["Echo-WM","LongCat"].includes(row.name)?"lb-logo-symbol":""}`} src={asset(`assets/models/${modelLogos[row.name]}.png`)} alt="" loading="lazy"/><span>{row.name}<small>{row.interface}</small></span><ChevronDown size={14} className={expanded===row.id?'open':''}/></button></div></th>{[-1,0,1,2,3,4,5].map(index=>{const position=rank(row,index);return <td key={index} className={`lb-value ${index===-1?'lb-overall':''}`} style={index>=0?{'--tier-color':tiers[index].color} as React.CSSProperties:undefined}><span className={position<=3?`lb-top lb-top-${position}`:''}>{format(score(row,index))}</span></td>})}</tr>{expanded===row.id&&<tr className="lb-expanded"><td colSpan={8}><div className="lb-detail"><div className="lb-specs"><strong>{row.name}</strong><dl><div><dt>Parameters (B)</dt><dd>{row.size||'Not reported'}</dd></div><div><dt>Sampling steps</dt><dd>{row.steps||'Not reported'}</dd></div><div><dt>3D representation</dt><dd>{row.representation===null?'Not specified':row.representation?'Explicit':'Implicit / none'}</dd></div><div><dt>Control</dt><dd>{row.interface}</dd></div></dl></div><div className="lb-bars">{tiers.map((t,i)=><div key={t.id}><span>{t.name}</span><div className="lb-track"><div style={{width:`${Math.max(0,Math.min(100,row.scores[i]))}%`,background:t.color}}/></div><b>{format(row.scores[i])}</b></div>)}</div></div></td></tr>}</Fragment>)}
  {filtered.length===0&&<tr><td colSpan={8} className="lb-empty">No models match these filters. <button onClick={()=>{setSearch('');setControl('All');setOnlySelected(false)}}>Reset filters</button></td></tr>}
  </tbody></table></div><div className="lb-legend"><span><i className="first"/>First</span><span><i className="second"/>Second</span><span><i className="third"/>Third</span><p>Ranks are calculated across all 27 models for each metric. Click a model for its profile.<br/>Control interfaces reflect the signals actually received by the model: direct action inputs are labeled Action; actions converted to camera parameters before model input are labeled Camera.</p></div>
 </div>;
}
