import {useEffect,useRef,useState} from 'react';
import {Play,Pause,RotateCcw,Maximize2,AlertCircle} from 'lucide-react';
import {tiers} from '../data/tiers';
import {media} from '../lib/assets';
import './MetricComparison.css';
import CameraPath from './CameraPath';

type Temporal={time:number;quality?:number|null;control?:number|null;geometry?:number|null};
type Model={id:string;name:string;video:string;poster:string;score:number|null;overallTierScore:number;evidence?:{return?:string;query?:string;first?:string;revisit?:string;depth?:string;render?:string;target?:string};temporal?:Temporal[]};
type Case={tier:number;caseId:string;source:string;template:string;prompt:string;duration:number;events:{name:string;frame:number;time:number}[];input:string;query?:string;trajectory:{points:number[][];angles:number[];events?:unknown[]};models:Model[]};
type Props={cases:Case[];rows?:unknown[]};
const seconds=(time:number)=>`${Math.floor(time/60)}:${Math.floor(time%60).toString().padStart(2,'0')}`;
const val=(n:number|null)=>n===null||!Number.isFinite(n)?'—':n.toFixed(2);
function Trajectory({trajectory,template}:{trajectory:Case['trajectory'];template:string}){return <CameraPath trajectory={trajectory} template={template} width={120} height={85} className="mc-path"/>;}
function Evidence({model,tier}:{model:Model;tier:number}){const labels:Partial<Record<keyof NonNullable<Model['evidence']>,string>>=tier===3?{query:'Query output',return:'Return'}:tier===4?{first:'First visit',revisit:'Revisit'}:{};const evidence=Object.entries(model.evidence||{}).filter(([key,value])=>labels[key as keyof typeof labels]&&value);if(!evidence.length)return null;return <details className="mc-evidence-details"><summary>View event frames</summary>{evidence.length>0&&<div className="mc-evidence">{evidence.map(([key,path])=><figure key={key}><img src={media(path!)} alt={`${model.name}: ${labels[key as keyof typeof labels]}`} loading="lazy"/><figcaption>{labels[key as keyof typeof labels]}</figcaption></figure>)}</div>}</details>}
export default function MetricComparison({cases}:Props){
 const [speed,setSpeed]=useState(1),[tier,setTier]=useState(1),[caseIndex,setCaseIndex]=useState(0),[playing,setPlaying]=useState(false),[time,setTime]=useState(0),[load,setLoad]=useState(false),[errors,setErrors]=useState<Record<number,boolean>>({}),[notice,setNotice]=useState(''),[showPrompt,setShowPrompt]=useState(false);
 const available=cases.filter(c=>c.tier===tier),current=available[Math.min(caseIndex,available.length-1)];
 const rankedModels=current?[...current.models].sort((a,b)=>(Number.isFinite(b.score)?b.score!: -Infinity)-(Number.isFinite(a.score)?a.score!: -Infinity)):[];
 const root=useRef<HTMLDivElement>(null),videos=useRef<(HTMLVideoElement|null)[]>([]),clock=useRef(0),visible=useRef(false),isPlaying=useRef(false),lastUpdate=useRef(0),caseVersion=useRef(0);
 const stop=()=>{videos.current.forEach(v=>v?.pause());isPlaying.current=false;setPlaying(false)};
 const seek=(next:number)=>{clock.current=next;setTime(next);videos.current.forEach(v=>{if(v&&v.readyState>=1)v.currentTime=Math.min(next,Number.isFinite(v.duration)?v.duration:next)})};
 useEffect(()=>{if(!root.current)return;const observer=new IntersectionObserver(([entry])=>{visible.current=entry.isIntersecting;if(entry.isIntersecting)setLoad(true);else stop()},{rootMargin:'0px',threshold:.05});observer.observe(root.current);return()=>observer.disconnect()},[]);
 useEffect(()=>{caseVersion.current+=1;const mountedVideos=[...videos.current];stop();clock.current=0;setTime(0);setErrors({});setNotice('');setShowPrompt(false);setLoad(visible.current);return()=>{mountedVideos.forEach(v=>{if(v){v.pause();v.removeAttribute('src');v.load()}})}},[tier,caseIndex]);
 useEffect(()=>{if(!playing)return;let frame=0;const tick=()=>{const master=videos.current.find(v=>v&&v.readyState>=2&&!v.paused);if(master){clock.current=master.currentTime;if(performance.now()-lastUpdate.current>80){setTime(master.currentTime);lastUpdate.current=performance.now()}videos.current.forEach(v=>{if(v&&v!==master&&!v.ended&&v.readyState>=2&&Math.abs(v.currentTime-master.currentTime)>.14)v.currentTime=Math.min(master.currentTime,v.duration)});if(current&&master.currentTime>=current.duration){seek(current.duration);stop();return}}frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[playing,current]);
 const play=async()=>{const version=caseVersion.current;setLoad(true);setNotice('');isPlaying.current=true;const active=videos.current.filter((v):v is HTMLVideoElement=>!!v&&!v.error);if(!active.length){setNotice('Videos are loading. Try Play again once the previews appear.');isPlaying.current=false;return}if(current&&clock.current>=current.duration-.1)seek(0);const results=await Promise.allSettled(active.map(v=>v.play()));if(!isPlaying.current||version!==caseVersion.current){active.forEach(v=>v.pause());return}const success=results.some(r=>r.status==='fulfilled');setPlaying(success);isPlaying.current=success;if(results.some(r=>r.status==='rejected'))setNotice('Some videos could not play. Retry the affected preview.')};
 useEffect(()=>{videos.current.forEach(video=>{if(video)video.playbackRate=speed})},[speed,tier,caseIndex]);
 const switchTier=(next:number)=>{stop();setTier(next);setCaseIndex(0)};
 if(!current)return <div className="mc-unavailable">Comparison media is unavailable.</div>;
 return <div className="mc-panel" ref={root}><div className="mc-tabs" role="tablist" aria-label="Evaluation metric">{tiers.map(t=><button key={t.id} id={`metric-tab-${t.id}`} role="tab" aria-selected={tier===t.id} aria-controls="metric-panel" tabIndex={tier===t.id?0:-1} onClick={()=>switchTier(t.id)} onKeyDown={event=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(event.key)){event.preventDefault();const next=event.key==='Home'?1:event.key==='End'?6:event.key==='ArrowRight'?tier%6+1:(tier+4)%6+1;switchTier(next);document.getElementById(`metric-tab-${next}`)?.focus()}}} className={tier===t.id?'active':''} style={{'--metric-color':t.color} as React.CSSProperties}>{t.short}</button>)}</div>
 <div id="metric-panel" role="tabpanel" aria-labelledby={`metric-tab-${tier}`}><div className="mc-casehead"><div><p>{tiers[tier-1].description.split('?')[0]}?</p></div><div className="mc-casebuttons">{available.map((c,i)=><button key={c.caseId} className={caseIndex===i?'active':''} onClick={()=>{stop();setCaseIndex(i)}} aria-pressed={caseIndex===i}>Case {i+1}</button>)}</div></div>
 <div className="mc-reference"><a className="mc-openframe" href={media(current.input)} target="_blank" rel="noreferrer" aria-label="Open input reference image"><img src={media(current.input)} alt={`Input image for ${current.caseId}`} loading="lazy"/></a><div><span>Input scene</span><p id="mc-scene-prompt" className={!showPrompt&&current.prompt.length>250?'mc-prompt-collapsed':undefined}>{current.prompt}</p>{current.prompt.length>250&&<button className="mc-description-toggle" aria-expanded={showPrompt} aria-controls="mc-scene-prompt" onClick={()=>setShowPrompt(!showPrompt)}>{showPrompt?'Show less':'Read full scene description'}</button>}</div><Trajectory trajectory={current.trajectory} template={current.template}/>{current.query&&<figure><a className="mc-openframe" href={media(current.query)} target="_blank" rel="noreferrer" aria-label="Open registered query reference image"><img src={media(current.query)} alt="Registered query reference" loading="lazy"/></a><figcaption>Query reference</figcaption></figure>}</div>
 <div className="mc-playerbar"><button className="mc-play" onClick={()=>playing?stop():void play()} aria-label={`${playing?'Pause':'Play'} all ${current.models.length} videos`}>{playing?<Pause size={17}/>:<Play size={17}/>} {playing?'Pause':'Play all'}</button><button className="mc-replay" onClick={()=>{seek(0);void play()}} aria-label="Replay all videos"><RotateCcw size={17}/></button><span className="mc-time">{seconds(time)}</span><input type="range" min={0} max={current.duration} step={.01} value={Math.min(time,current.duration)} onChange={e=>seek(Number(e.target.value))} aria-label="Shared video timeline"/><span className="mc-time">{seconds(current.duration)}</span><label className="mc-speed"><span>Speed</span><select aria-label="Playback speed" value={speed} onChange={event=>setSpeed(Number(event.target.value))}>{[.5,1,1.5,2].map(rate=><option key={rate} value={rate}>{rate}×</option>)}</select></label></div>
 {current.events.length>0&&<div className="mc-events"><span>Jump to</span>{current.events.map((event,i)=><button key={`${event.name}-${i}`} onClick={()=>seek(Math.min(event.time,current.duration))} title={`Frame ${event.frame}`} className={Math.abs(time-event.time)<.6?'active':''}>{event.name}<small>{seconds(event.time)}</small></button>)}</div>}
 {notice&&<p className="mc-notice" role="status">{notice}</p>}
 <div className={`mc-grid${current.models.length===7?' mc-grid-seven':''}`} key={`${tier}-${current.caseId}`}>{rankedModels.map((model,index)=><article className="mc-modelcard" key={model.id}><header><strong>{model.name}</strong><span title="Score on this case">Case <b>{val(model.score)}</b></span></header><div className="mc-videowrap"><video ref={node=>{videos.current[index]=node}} src={load?media(model.video):undefined} poster={media(model.poster)} preload="metadata" muted playsInline onLoadedMetadata={e=>{const video=e.currentTarget;video.playbackRate=speed;video.currentTime=Math.min(clock.current,video.duration);if(isPlaying.current)void video.play().catch(()=>{})}} onError={()=>setErrors(old=>({...old,[index]:true}))} onEnded={()=>{if(videos.current.every(v=>!v||v.ended||v.error))stop()}} aria-label={`${model.name} generated rollout`}/>{errors[index]?<div className="mc-videoerror"><AlertCircle size={20}/><p>Preview could not load.</p><button onClick={()=>{setErrors(old=>({...old,[index]:false}));videos.current[index]?.load()}}>Retry preview</button></div>:<button className="mc-fullscreen" aria-label={`Fullscreen ${model.name}`} onClick={()=>{const v=videos.current[index];if(v?.requestFullscreen)void v.requestFullscreen()}}><Maximize2 size={15}/></button>}</div><footer><span>Overall {tiers[tier-1].short}</span><b>{val(model.overallTierScore)}</b></footer><Evidence model={model} tier={tier}/></article>)}</div><p className="mc-footnote">Case scores evaluate this rollout. Overall scores are the model’s aggregate on the selected tier. All videos use the same playback speed. The timeline and event timestamps remain in original rollout time.</p></div>
 </div>;
}
